### ISSUE TITLE
Change the preview gif to the new design

### ISSUE THREAD

**Issue by origranot** [origranot/reduced.to#588] opened 2023-11-28 17:43 UTC
### What would you like to share?

We should change the current README preview.gif to the new design.
I personally prefer the dark theme 😄

**Comment by Mohsin-mw** [comment] 2023-12-05 14:00
**Subject:** Request to Assign README Preview.gif Design Update Issue

Hi @origranot,

Could you please assign this issue to me? I'd like to contribute by implementing the changes and ensuring the README accurately reflects the new design, including the dark theme.

Looking forward to your response!

Best regards,
@mohsin-mw

**Comment by origranot** [comment] 2023-12-24 19:56
@Mohsin-mw How it's going, do you need any help with the issue?

**Comment by Siddharth1605** [comment] 2023-12-29 14:35
@origranot if the issue is not yet closed, can you assign it to me.

**Comment by origranot** [comment] 2023-12-29 14:39
> @origranot if the issue is not yet closed, can you assign it to me.

Go for it champ!

**Comment by gsi-kevincarrera** [comment] 2023-12-29 17:00
I already did it, but I do not want to get in between if someone else is on it. You can assing it to me, if the other user do not do it either

**Comment by Siddharth1605** [comment] 2023-12-29 17:11
@origranot assign this issue to @gsi-kevincarrera , he says he already did it

**Closed** 2024-10-01 14:00 UTC
Labels: documentation, good first issue
