### ISSUE TITLE
QR Code pop-up

### ISSUE THREAD

**Issue by rahultg1411** [origranot/reduced.to#489] opened 2023-10-04 21:24 UTC
### Description

Currently, the download button for the generated QR is barely visible in my browser at 100% zoom. I had a feature suggestion where, upon clicking on the generate QR button, a pop-up is triggered with the QR code with the download button and a button to close the pop as well. 

### Screenshots

![image](https://github.com/origranot/reduced.to/assets/84085307/c1d7bf75-e2ee-4948-a0c5-aa7221e89e2c)

### Additional information

I would love to work on this if the feature request is accepted.

**Comment by origranot** [comment] 2023-10-04 21:28
Hey, it's a duplicate of https://github.com/origranot/reduced.to/issues/477

**Closed by origranot** 2023-10-04 21:28 UTC
Labels: enhancement, triage
